services:
  load_balancer:
    image: nginx:alpine
    container_name: load_balancer
    ports:
      - "80:80"
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - user_plane
      - internal

  web_server_1:
    image: nginx:alpine
    container_name: web_server_1
    volumes:
      - ./web/content:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal

  web_server_2:
    image: nginx:alpine
    container_name: web_server_2
    volumes:
      - ./web2/content:/usr/share/nginx/html
      - ./web2/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal

networks:
  user_plane:
    driver: bridge
  internal:
    driver: bridge